# Generated by Django 5.2.6 on 2025-09-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="tag",
            name="display_name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
