# Generated by Django 5.2.6 on 2025-10-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_post_views_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
