# Generated by Django 5.2.6 on 2025-10-06 10:59

import datetime
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveStream",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=100)),
                (
                    "privacy",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("friends", "Friends Only"),
                            ("private", "Private"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("live", "Live"),
                            ("ended", "Ended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "stream_key",
                    models.CharField(editable=False, max_length=100, unique=True),
                ),
                ("rtmp_url", models.CharField(blank=True, max_length=500)),
                ("playback_url", models.CharField(blank=True, max_length=500)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="stream_thumbnails/"
                    ),
                ),
                ("viewer_count", models.PositiveIntegerField(default=0)),
                ("peak_viewers", models.PositiveIntegerField(default=0)),
                ("total_views", models.PositiveIntegerField(default=0)),
                ("duration", models.DurationField(blank=True, null=True)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "streamer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_streams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StreamAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_messages", models.PositiveIntegerField(default=0)),
                ("total_reactions", models.PositiveIntegerField(default=0)),
                (
                    "average_watch_time",
                    models.DurationField(default=datetime.timedelta(0)),
                ),
                ("peak_concurrent_viewers", models.PositiveIntegerField(default=0)),
                ("average_bitrate", models.FloatField(default=0)),
                ("buffering_ratio", models.FloatField(default=0)),
                ("error_rate", models.FloatField(default=0)),
                (
                    "total_donations",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_super_chats",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stream",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="livestream.livestream",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StreamBan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "banned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_stream_bans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bans",
                        to="livestream.livestream",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stream_bans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StreamMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("chat", "Chat Message"),
                            ("donation", "Donation"),
                            ("super_chat", "Super Chat"),
                            ("system", "System Message"),
                        ],
                        default="chat",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("is_flagged", models.BooleanField(default=False)),
                ("flag_count", models.PositiveIntegerField(default=0)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("is_moderated", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "moderated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderated_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="livestream.livestream",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stream_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="StreamModerationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_logs",
                        to="livestream.livestream",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StreamParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("viewer", "Viewer"),
                            ("guest", "Guest"),
                            ("moderator", "Moderator"),
                        ],
                        default="viewer",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("watch_time", models.DurationField(default=datetime.timedelta(0))),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="livestream.livestream",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stream_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StreamReaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("like", "👍 Like"),
                            ("love", "❤️ Love"),
                            ("laugh", "😂 Laugh"),
                            ("wow", "😮 Wow"),
                            ("sad", "😢 Sad"),
                            ("angry", "😠 Angry"),
                            ("fire", "🔥 Fire"),
                            ("heart", "💖 Heart"),
                        ],
                        default="like",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="livestream.livestream",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stream_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="livestream",
            index=models.Index(
                fields=["streamer", "status"], name="livestream__streame_23b784_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="livestream",
            index=models.Index(
                fields=["status", "privacy"], name="livestream__status_e44c27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="livestream",
            index=models.Index(
                fields=["stream_key"], name="livestream__stream__6e6849_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="streamban",
            index=models.Index(
                fields=["stream", "user"], name="livestream__stream__2282b3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="streamban",
            unique_together={("stream", "user")},
        ),
        migrations.AddIndex(
            model_name="streammessage",
            index=models.Index(
                fields=["stream", "timestamp"], name="livestream__stream__f5eb33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="streammessage",
            index=models.Index(
                fields=["user", "timestamp"], name="livestream__user_id_08b4ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="streamparticipant",
            index=models.Index(
                fields=["stream", "user"], name="livestream__stream__87a59c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="streamparticipant",
            index=models.Index(
                fields=["user", "joined_at"], name="livestream__user_id_f2ee7f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="streamparticipant",
            unique_together={("stream", "user")},
        ),
        migrations.AddIndex(
            model_name="streamreaction",
            index=models.Index(
                fields=["stream", "reaction_type"],
                name="livestream__stream__60e4bc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="streamreaction",
            index=models.Index(
                fields=["user", "timestamp"], name="livestream__user_id_7cbbe4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="streamreaction",
            unique_together={("stream", "user", "reaction_type")},
        ),
    ]
