# Generated by Django 5.2.6 on 2025-10-09 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livestream", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StreamRecording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_file", models.FileField(upload_to="stream_recordings/")),
                ("duration", models.DurationField()),
                ("file_size", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="livestream",
            name="age_restriction",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="livestream",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="livestream",
            name="language",
            field=models.CharField(default="en", max_length=10),
        ),
        migrations.AddField(
            model_name="livestream",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name="livestream",
            index=models.Index(
                fields=["category"], name="livestream__categor_c09bdd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="livestream",
            index=models.Index(
                fields=["is_featured", "status"], name="livestream__is_feat_8268e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="livestream",
            index=models.Index(
                fields=["created_at", "status"], name="livestream__created_f2b1b7_idx"
            ),
        ),
        migrations.AddField(
            model_name="streamrecording",
            name="stream",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recording",
                to="livestream.livestream",
            ),
        ),
    ]
