# Generated by Django 5.2.6 on 2025-09-18 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="education",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="education"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="friends_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="hobbies",
            field=models.TextField(blank=True, verbose_name="hobbies"),
        ),
        migrations.AddField(
            model_name="profile",
            name="interests",
            field=models.TextField(blank=True, verbose_name="interests"),
        ),
        migrations.AddField(
            model_name="profile",
            name="relationship_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single"),
                    ("in_relationship", "In a relationship"),
                    ("married", "Married"),
                    ("complicated", "It’s complicated"),
                ],
                max_length=20,
                verbose_name="relationship status",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="work",
            field=models.CharField(blank=True, max_length=100, verbose_name="work"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=models.CharField(blank=True, max_length=100, verbose_name="location"),
        ),
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_requests_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_requests_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("requester", "receiver")},
            },
        ),
    ]
