# Generated by Django 5.2.6 on 2025-10-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='dark_mode',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=20),
        ),
    ]
