# Generated by Django 5.2.6 on 2025-10-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_usersettings_dark_mode_usersettings_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="cover_photo",
            field=models.ImageField(blank=True, null=True, upload_to="covers/"),
        ),
    ]
