# Generated by Django 5.2.6 on 2025-10-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usersettings_allow_follow_requests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='color_blind_mode',
            field=models.BooleanField(default=False, help_text='Optimize colors for color vision deficiency'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='font_size',
            field=models.PositiveIntegerField(default=16, help_text='Base font size in pixels'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='high_contrast',
            field=models.BooleanField(default=False, help_text='Increase color contrast for better visibility'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='layout_density',
            field=models.CharField(choices=[('comfortable', 'Comfortable'), ('compact', 'Compact')], default='comfortable', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='reduced_motion',
            field=models.BooleanField(default=False, help_text='Reduce animations and transitions'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('de', 'Deutsch'), ('zh', '中文')], default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System'), ('blue', 'Ocean'), ('green', 'Forest'), ('purple', 'Royal')], default='light', max_length=20),
        ),
    ]
