# Generated by Django 5.2.6 on 2025-10-31 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reaction",
            options={"ordering": ["-created_at"]},
        ),
    ]
