# Generated by Django 5.2.6 on 2025-11-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0003_commentattachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
