# Generated by Django 5.2.6 on 2025-10-21 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="directmessage",
            options={"ordering": ["created_at"]},
        ),
        migrations.RemoveField(
            model_name="directmessage",
            name="post_url",
        ),
        migrations.AddField(
            model_name="directmessage",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="messages/attachments/"
            ),
        ),
        migrations.AddField(
            model_name="directmessage",
            name="conversation_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="directmessage",
            name="deleted_by_recipient",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="directmessage",
            name="deleted_by_sender",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="directmessage",
            name="delivered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="directmessage",
            name="in_reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="messaging.directmessage",
            ),
        ),
        migrations.AddField(
            model_name="directmessage",
            name="read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="directmessage",
            index=models.Index(
                fields=["conversation_key", "-created_at"],
                name="messaging_d_convers_c43682_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="directmessage",
            index=models.Index(
                fields=["sender", "recipient", "created_at"],
                name="messaging_d_sender__cf9d78_idx",
            ),
        ),
    ]
