# Generated by Django 5.2.6 on 2025-10-06 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_friend_requests", models.BooleanField(default=True)),
                ("email_friend_acceptances", models.BooleanField(default=True)),
                ("email_post_likes", models.BooleanField(default=True)),
                ("email_post_comments", models.BooleanField(default=True)),
                ("email_comment_replies", models.BooleanField(default=True)),
                ("email_mentions", models.BooleanField(default=True)),
                ("email_messages", models.BooleanField(default=False)),
                ("email_system", models.BooleanField(default=True)),
                ("push_friend_requests", models.BooleanField(default=True)),
                ("push_friend_acceptances", models.BooleanField(default=True)),
                ("push_post_likes", models.BooleanField(default=True)),
                ("push_post_comments", models.BooleanField(default=True)),
                ("push_comment_replies", models.BooleanField(default=True)),
                ("push_mentions", models.BooleanField(default=True)),
                ("push_messages", models.BooleanField(default=True)),
                ("push_system", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("friend_request", "Friend Request"),
                            ("friend_accepted", "Friend Request Accepted"),
                            ("post_like", "Post Like"),
                            ("post_comment", "Post Comment"),
                            ("comment_reply", "Comment Reply"),
                            ("message", "New Message"),
                            ("post_mention", "Post Mention"),
                            ("comment_mention", "Comment Mention"),
                            ("system", "System Notification"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "created_at"],
                        name="notificatio_recipie_86ea8b_idx",
                    )
                ],
            },
        ),
    ]
